# Generated by Django 2.1.3 on 2018-11-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181117_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'unknown'), ('1', '正常'), ('2', '崩溃'), ('3', '失败')], default='0', max_length=16)),
                ('process_cpu', models.CharField(max_length=16)),
                ('peak_cpu', models.CharField(max_length=16)),
                ('total_cpu', models.CharField(max_length=16)),
                ('process_mem', models.CharField(max_length=16)),
                ('peak_mem', models.CharField(max_length=16)),
                ('used_mem', models.CharField(max_length=16)),
                ('used_gpu', models.CharField(max_length=16)),
                ('peak_gpu', models.CharField(max_length=16)),
                ('product', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('qrcode', models.CharField(max_length=64)),
                ('screenshot', models.CharField(max_length=64)),
                ('video_coding', models.CharField(max_length=255)),
                ('audio_coding', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=16)),
                ('distinguishability', models.CharField(max_length=16)),
                ('subtitle', models.BooleanField(default=False)),
                ('audio_track', models.IntegerField(default=1, verbose_name='音轨数量')),
            ],
        ),
        migrations.AddField(
            model_name='playrecord',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Video'),
        ),
    ]
