# Generated by Django 2.1.3 on 2018-12-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181130_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ftpurl',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='httpurl',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
