# Generated by Django 2.1.3 on 2019-01-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20181201_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='avg_frame_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=5, verbose_name='平均帧率'),
        ),
        migrations.AddField(
            model_name='video',
            name='bit_rate',
            field=models.IntegerField(blank=True, default=-1, verbose_name='码率'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, default=-1, verbose_name='时长'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(blank=True, default=-1, verbose_name='高'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(blank=True, default=-1, verbose_name='宽'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='distinguishability',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
