# Generated by Django 2.1.3 on 2019-01-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190128_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtitle',
            field=models.IntegerField(blank=True, verbose_name='字幕数'),
        ),
    ]
