# Generated by Django 2.1.3 on 2019-01-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20190129_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subtitle',
        ),
    ]
