# Generated by Django 2.1.3 on 2018-12-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20181219_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='height',
            field=models.IntegerField(blank=True, verbose_name='高'),
        ),
        migrations.AlterField(
            model_name='video',
            name='width',
            field=models.IntegerField(blank=True, verbose_name='宽'),
        ),
    ]
