# Generated by Django 2.1.3 on 2019-01-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_remove_video_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle',
            field=models.IntegerField(blank=True, default=0, verbose_name='字幕数'),
            preserve_default=False,
        ),
    ]
