# Generated by Django 2.1.3 on 2019-01-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_video_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='audio_coding',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='audio_track',
            field=models.IntegerField(default=1, null=True, verbose_name='音轨数量'),
        ),
        migrations.AlterField(
            model_name='video',
            name='avg_frame_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=5, null=True, verbose_name='平均帧率'),
        ),
        migrations.AlterField(
            model_name='video',
            name='bit_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='码率'),
        ),
        migrations.AlterField(
            model_name='video',
            name='distinguishability',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='video',
            name='format',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='高'),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='qrcode',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='screenshot',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitle',
            field=models.IntegerField(blank=True, null=True, verbose_name='字幕数'),
        ),
        migrations.AlterField(
            model_name='video',
            name='suffix',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_coding',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='宽'),
        ),
    ]
