# Generated by Django 2.1.3 on 2019-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20190129_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='ftpurl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
