# Generated by Django 2.1.3 on 2019-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20190129_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='httpurl',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
